# ----------------------------------------------------------------------------------------------------
# Pipeline to scan/build an app upon Pull Request
# See readme file for more info about variable group "DurableDemo"
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest
variables:
  - group: aspireapp.blazor.net8.web

# ----------------------------------------------------------------------------------------------------
# FYI - Set a required branch policy to run this on every check to main 
# ----------------------------------------------------------------------------------------------------
# trigger:
#   - none
pr:
- main

# ----------------------------------------------------------------------------------------------------
stages:
  - template: pipes/build-only-pipe.yml
    parameters:
      runUnitTests: ${{ parameters.runUnitTests }}
      runUITests: 'false'
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}
