# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build and deploy Application Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: runGHASScan
  default: 'false'
- name: runMSDevSecOpsScan
  default: 'false'
- name: runUnitTests
  default: 'false'
- name: runUITests
  default: 'false'

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEV'
        runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
        runGHASScan: ${{ parameters.runGHASScan }}

# ----------------------------------------------------------------------------------------------------
- stage: BuildWebApp
  displayName: Build WebApp
  jobs:
  - template: templates/build-webapp-template.yml
    parameters:
      environmentName: 'DEV'
      runUnitTests: ${{ parameters.runUnitTests }}
